project:
  type: website

website:
  site-url: https://markus1bauer.github.io/
  title: "homepage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




babelquarto:
  languagelinks: navbar
  languagecodes:
  - name: en
    text: "Version in en"
  - name: de
    text: "Version in de"
  mainlanguage: 'de'
  languages: ['en']
title-en: title in en
description-en: description in en
author-en: author in en
lang: de
